export { default as studentController } from '@controller/students'
export { default as authController } from '@controller/auth'
export { default as cohortController } from '@controller/cohort'
export { default as trainerController } from '@controller/trainer'
export { default as roleController } from '@controller/role'
