export { default as studentController } from '@controller/student'
export { default as authController } from '@controller/auth'
export { default as cohortController } from '@controller/cohort'
export { default as trainerController } from '@controller/trainer'
export { default as roleController } from '@controller/role'
export { default as moduleController } from '@controller/module'
export { default as statusController } from '@controller/status'
export { default as exerciseController } from '@controller/exercise'
