export { default as Student } from '@models/Student'
export { default as Trainer } from '@models/Trainer'
export { default as Cohort } from '@models/Cohort'
export { default as Recording } from '@models/Recording'
export { default as Timetable } from '@models/Timetable'
